name: Executar minha action
on:
  push:
    branches:
      - main
jobs:
  python-action:
    runs-on: ubuntu-latest
    steps:

      - name: Usar a ação personalizada
        id: colaborador
        uses: lccinacio/actions/action-python@v20.0
        with:
          nome: 'Lucas'
          sobrenome: 'Inacio'
          cargo: 'Engenheiro de qualidade'