name: Executar minha action
on:
  push:
    branches:
      - main
jobs:
  python-action:
    runs-on: ubuntu-latest
    steps:

      - name: Usar a ação personalizada test
        id: colaborador
        uses: lccinacio/action-python@main
        with:
          nome: 'Lucas'
          sobrenome: 'Inacio'
          cargo: 'Engenheiro de qualidade'